outpkg: "{{.PackageName}}"
filename: "mock_{{ .InterfaceName | snakecase }}.go"
mockname: "Mock{{.InterfaceName}}"
with-expecter: true
all: true # generate all interface
dir: "internal/mocks/{{.PackageName}}"
packages:
  github.com/huytran2000-hcmus/bTaskee/booking/internal/repository:
