version: "3"

services:
  mongodb:
    image: mongo:7.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: btaskee
      MONGO_INITDB_ROOT_PASSWORD: secret 
    volumes:
      - 'mongodbdata:/data/db'
    ports:
      - "27017:27017"
  booking:
    build: ./booking/
    environment:
      PORT: 8080
      DB_URI: mongodb://btaskee:secret@mongodb:27017
      DB_NAME: booking
      CALCULATE_PRICE_URI: http://pricing:8081/api/v1/task:calculate-price
      SEND_TASK_ID: http://send:8082/api/v1/task:send
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
  pricing:
    build: ./pricing/
    environment:
      PORT: 8081
    ports:
      - "8081:8081"
  send:
    build: ./send/
    environment:
      PORT: 8082
      EMAIL_API_KEY: $EMAIL_API_KEY
    ports:
      - "8082:8082"
volumes:
  mongodbdata:
