definitions:
  model.Customer:
    properties:
      email:
        example: huy@gmail.com
        type: string
      name:
        example: huy tran
        type: string
      phone:
        example: "+84948447524"
        type: string
    required:
    - email
    - name
    - phone
    type: object
  model.Location:
    properties:
      address:
        example: 60 Bến Thành, Quận 1, TP.Hồ Chí Minh
        type: string
    required:
    - address
    type: object
  model.SendTaskRequest:
    properties:
      assigned_location:
        $ref: '#/definitions/model.Location'
      customer:
        $ref: '#/definitions/model.Customer'
      id:
        example: c4824b96-e4ca-49cf-aaea-156604799612
        type: string
      note:
        example: Be here ontime
        type: string
      tasker:
        $ref: '#/definitions/model.Tasker'
      total:
        example: 400
        type: number
      working_details:
        $ref: '#/definitions/model.WorkingDetails'
    required:
    - assigned_location
    - customer
    - id
    - tasker
    - total
    - working_details
    type: object
  model.SendTaskResponse:
    properties:
      message_ids:
        items:
          type: string
        type: array
    type: object
  model.Tasker:
    properties:
      email:
        example: <enter your email here>
        type: string
      name:
        example: huy tran
        type: string
      phone:
        example: "+84948447525"
        type: string
    required:
    - email
    - name
    - phone
    type: object
  model.WorkingDetails:
    properties:
      from_time:
        example: "2024-04-07T09:00:00+07:00"
        type: string
      house_type:
        example: two_room
        type: string
      service_types:
        example:
        - cleaning
        - childcare
        items:
          type: string
        minItems: 1
        type: array
      to_time:
        example: "2024-04-07T11:00:00+07:00"
        type: string
    required:
    - from_time
    - house_type
    - service_types
    - to_time
    type: object
  restful.errorResponse:
    properties:
      error:
        type: string
    type: object
  restful.successResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: This is send apis
  title: Send API
  version: "1.0"
paths:
  /api/v1/task:send:
    post:
      consumes:
      - application/json
      description: Send task to tasker
      parameters:
      - description: Send Task Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SendTaskRequest'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/restful.successResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.SendTaskResponse'
              type: object
        "400":
          description: bad request
          schema:
            $ref: '#/definitions/restful.errorResponse'
      summary: Send task to tasker
      tags:
      - Task
swagger: "2.0"
