// Code generated by go-swagger; DO NOT EDIT.

package dto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelTask model task
//
// swagger:model model.Task
type ModelTask struct {

	// assigned location
	AssignedLocation *ModelLocation `json:"assigned_location,omitempty"`

	// customer
	Customer *ModelCustomer `json:"customer,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// note
	Note string `json:"note,omitempty"`

	// tasker
	Tasker *ModelTasker `json:"tasker,omitempty"`

	// total
	Total float64 `json:"total,omitempty"`

	// working details
	WorkingDetails *ModelWorkingDetails `json:"working_details,omitempty"`
}

// Validate validates this model task
func (m *ModelTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAssignedLocation(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomer(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTasker(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkingDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelTask) validateAssignedLocation(formats strfmt.Registry) error {
	if swag.IsZero(m.AssignedLocation) { // not required
		return nil
	}

	if m.AssignedLocation != nil {
		if err := m.AssignedLocation.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assigned_location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("assigned_location")
			}
			return err
		}
	}

	return nil
}

func (m *ModelTask) validateCustomer(formats strfmt.Registry) error {
	if swag.IsZero(m.Customer) { // not required
		return nil
	}

	if m.Customer != nil {
		if err := m.Customer.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("customer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("customer")
			}
			return err
		}
	}

	return nil
}

func (m *ModelTask) validateTasker(formats strfmt.Registry) error {
	if swag.IsZero(m.Tasker) { // not required
		return nil
	}

	if m.Tasker != nil {
		if err := m.Tasker.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tasker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tasker")
			}
			return err
		}
	}

	return nil
}

func (m *ModelTask) validateWorkingDetails(formats strfmt.Registry) error {
	if swag.IsZero(m.WorkingDetails) { // not required
		return nil
	}

	if m.WorkingDetails != nil {
		if err := m.WorkingDetails.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("working_details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("working_details")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this model task based on the context it is used
func (m *ModelTask) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAssignedLocation(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateCustomer(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateTasker(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorkingDetails(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelTask) contextValidateAssignedLocation(ctx context.Context, formats strfmt.Registry) error {

	if m.AssignedLocation != nil {

		if swag.IsZero(m.AssignedLocation) { // not required
			return nil
		}

		if err := m.AssignedLocation.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("assigned_location")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("assigned_location")
			}
			return err
		}
	}

	return nil
}

func (m *ModelTask) contextValidateCustomer(ctx context.Context, formats strfmt.Registry) error {

	if m.Customer != nil {

		if swag.IsZero(m.Customer) { // not required
			return nil
		}

		if err := m.Customer.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("customer")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("customer")
			}
			return err
		}
	}

	return nil
}

func (m *ModelTask) contextValidateTasker(ctx context.Context, formats strfmt.Registry) error {

	if m.Tasker != nil {

		if swag.IsZero(m.Tasker) { // not required
			return nil
		}

		if err := m.Tasker.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tasker")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("tasker")
			}
			return err
		}
	}

	return nil
}

func (m *ModelTask) contextValidateWorkingDetails(ctx context.Context, formats strfmt.Registry) error {

	if m.WorkingDetails != nil {

		if swag.IsZero(m.WorkingDetails) { // not required
			return nil
		}

		if err := m.WorkingDetails.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("working_details")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("working_details")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ModelTask) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelTask) UnmarshalBinary(b []byte) error {
	var res ModelTask
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
