// Code generated by go-swagger; DO NOT EDIT.

package dto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelIdentification model identification
//
// swagger:model model.Identification
type ModelIdentification struct {

	// cccd
	// Example: 999999999999
	Cccd string `json:"cccd,omitempty"`

	// cmnd
	// Example: 888888888
	Cmnd string `json:"cmnd,omitempty"`
}

// Validate validates this model identification
func (m *ModelIdentification) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this model identification based on context it is used
func (m *ModelIdentification) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ModelIdentification) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelIdentification) UnmarshalBinary(b []byte) error {
	var res ModelIdentification
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
