// Code generated by go-swagger; DO NOT EDIT.

package dto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestfulSuccessResponse restful success response
//
// swagger:model restful.successResponse
type RestfulSuccessResponse struct {

	// data
	Data interface{} `json:"data,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this restful success response
func (m *RestfulSuccessResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this restful success response based on context it is used
func (m *RestfulSuccessResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestfulSuccessResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestfulSuccessResponse) UnmarshalBinary(b []byte) error {
	var res RestfulSuccessResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
