// Code generated by go-swagger; DO NOT EDIT.

package dto

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestfulErrorResponse restful error response
//
// swagger:model restful.errorResponse
type RestfulErrorResponse struct {

	// error
	Error string `json:"error,omitempty"`
}

// Validate validates this restful error response
func (m *RestfulErrorResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this restful error response based on context it is used
func (m *RestfulErrorResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestfulErrorResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestfulErrorResponse) UnmarshalBinary(b []byte) error {
	var res RestfulErrorResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
