// Code generated by go-swagger; DO NOT EDIT.

package task

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/huytran2000-hcmus/bTaskee/booking/booking_client/dto"
)

// NewPostAPIV1TasksParams creates a new PostAPIV1TasksParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV1TasksParams() *PostAPIV1TasksParams {
	return &PostAPIV1TasksParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV1TasksParamsWithTimeout creates a new PostAPIV1TasksParams object
// with the ability to set a timeout on a request.
func NewPostAPIV1TasksParamsWithTimeout(timeout time.Duration) *PostAPIV1TasksParams {
	return &PostAPIV1TasksParams{
		timeout: timeout,
	}
}

// NewPostAPIV1TasksParamsWithContext creates a new PostAPIV1TasksParams object
// with the ability to set a context for a request.
func NewPostAPIV1TasksParamsWithContext(ctx context.Context) *PostAPIV1TasksParams {
	return &PostAPIV1TasksParams{
		Context: ctx,
	}
}

// NewPostAPIV1TasksParamsWithHTTPClient creates a new PostAPIV1TasksParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV1TasksParamsWithHTTPClient(client *http.Client) *PostAPIV1TasksParams {
	return &PostAPIV1TasksParams{
		HTTPClient: client,
	}
}

/*
PostAPIV1TasksParams contains all the parameters to send to the API endpoint

	for the post API v1 tasks operation.

	Typically these are written to a http.Request.
*/
type PostAPIV1TasksParams struct {

	/* Request.

	   Create Task Request
	*/
	Request *dto.ModelCreateTaskRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v1 tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1TasksParams) WithDefaults() *PostAPIV1TasksParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v1 tasks params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV1TasksParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v1 tasks params
func (o *PostAPIV1TasksParams) WithTimeout(timeout time.Duration) *PostAPIV1TasksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v1 tasks params
func (o *PostAPIV1TasksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v1 tasks params
func (o *PostAPIV1TasksParams) WithContext(ctx context.Context) *PostAPIV1TasksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v1 tasks params
func (o *PostAPIV1TasksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v1 tasks params
func (o *PostAPIV1TasksParams) WithHTTPClient(client *http.Client) *PostAPIV1TasksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v1 tasks params
func (o *PostAPIV1TasksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post API v1 tasks params
func (o *PostAPIV1TasksParams) WithRequest(request *dto.ModelCreateTaskRequest) *PostAPIV1TasksParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post API v1 tasks params
func (o *PostAPIV1TasksParams) SetRequest(request *dto.ModelCreateTaskRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV1TasksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
